import { Module, DynamicModule, Global } from "@nestjs/common";
import path from "path";
import { SchemaConfig } from "../types";
import { validateSchema } from "../engine";
import jiti from "jiti";
import { runEnvSyncBuild } from "./utils";

export interface EnvSyncModuleOptions {
  configPath?: string;
  isGlobal?: boolean;
}

@Global()
@Module({})
export class EnvSyncModule {
  static forRoot(options: EnvSyncModuleOptions = {}): DynamicModule {
    const configPath = options.configPath || path.resolve(process.cwd(), "envsync.config.ts");
    
    // First ensure code is generated by running CLI build
    runEnvSyncBuild("NestJS");

    // Load config dynamically to provide the serverEnv instance
    const loadConfig = jiti(process.cwd(), { interopDefault: true });
    const config = loadConfig(configPath) as SchemaConfig;

    const { server, client, success } = validateSchema(config);
    if (!success) {
      // Collect all error messages and throw — never call process.exit in library code
      const allErrors = [...server.errors, ...client.errors]
        .map(e => `  [${e.key}]: ${e.message}`)
        .join("\n");
      throw new Error(`[EnvSync] Environment validation failed:\n${allErrors}`);
    }

    const providers = [
      {
        provide: "SERVER_ENV",
        useValue: server.data,
      },
      {
        provide: "CLIENT_ENV",
        useValue: client.data,
      }
    ];

    return {
      module: EnvSyncModule,
      global: options.isGlobal !== false,
      providers,
      exports: providers,
    };
  }
}
