import { Module, DynamicModule, Global } from "@nestjs/common";
import { execFileSync } from "child_process";
import fs from "fs";
import path from "path";
import { SchemaConfig } from "../types";
import { validateSchema } from "../engine";
import jiti from "jiti";

export interface EnvSyncModuleOptions {
  configPath?: string;
  isGlobal?: boolean;
}

@Global()
@Module({})
export class EnvSyncModule {
  static forRoot(options: EnvSyncModuleOptions = {}): DynamicModule {
    const configPath = options.configPath || path.resolve(process.cwd(), "envsync.config.ts");
    
    let config: SchemaConfig;
    try {
      // First ensure code is generated by running CLI build
      const cliPath = path.resolve(process.cwd(), "node_modules/.bin/envsync");
      if (fs.existsSync(cliPath)) {
        execFileSync(process.execPath, [cliPath, "build"], { stdio: "inherit" });
      } else {
        const localCli = path.resolve(process.cwd(), "dist/cli.js");
        if (fs.existsSync(localCli)) {
          execFileSync(process.execPath, [localCli, "build"], { stdio: "inherit" });
        }
      }

      // Load config dynamically to provide the serverEnv instance
      const loadConfig = jiti(process.cwd(), { interopDefault: true });
      config = loadConfig(configPath) as SchemaConfig;
    } catch (e: any) {
      console.error("❌ EnvSync Module startup failed.");
      process.exit(1);
    }

    const { server, client, success } = validateSchema(config);
    if (!success) {
      process.exit(1);
    }

    const providers = [
      {
        provide: "SERVER_ENV",
        useValue: server.data,
      },
      {
        provide: "CLIENT_ENV",
        useValue: client.data,
      }
    ];

    return {
      module: EnvSyncModule,
      global: options.isGlobal !== false,
      providers,
      exports: providers,
    };
  }
}
