import fs from "fs";
import path from "path";
import { SchemaConfig, FieldDef } from "./types";

const PREFIX_MAP: Record<string, string> = {
  nextjs: "NEXT_PUBLIC_",
  vite: "VITE_",
  cra: "REACT_APP_",
  sveltekit: "PUBLIC_",
  nuxt: "NUXT_PUBLIC_",
};

/** Regex for a valid JS identifier — must match exactly to be safe to splice into generated source. */
const SAFE_IDENTIFIER_RE = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;

/**
 * Validates that a schema key is a safe JavaScript identifier.
 * Throws with a descriptive error if it isn't, preventing code injection in generated files.
 */
function assertSafeIdentifier(key: string, context: string): void {
  if (!SAFE_IDENTIFIER_RE.test(key)) {
    throw new Error(
      `[EnvSync] Unsafe key detected in ${context}: "${key}". ` +
      `Keys must be valid JavaScript identifiers (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/).`
    );
  }
}

function getFieldTsType(def: FieldDef): string {
  switch (def.type) {
    case "string":
    case "url":
    case "email":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      return "any[]";
    case "json":
      return "Record<string, any>";
    case "enum":
      // JSON.stringify each value to safely escape quotes/special chars
      return def.values.map(v => JSON.stringify(v)).join(" | ");
    default:
      return "any";
  }
}

/**
 * Builds a minimal, safe JSON representation of a FieldDef for embedding in generated files.
 * Only serializes `type` and `default` — strips everything else (e.g., `required`, `allowInClient`,
 * `values`) to avoid leaking schema metadata into the client bundle and to minimize bundle size.
 */
function serializeDefForRuntime(def: FieldDef): string {
  const minimal: Record<string, any> = { type: def.type };
  if (def.default !== undefined) {
    minimal.default = def.default;
  }
  // For enum, include values so __coerce can fall through correctly
  if (def.type === "enum") {
    minimal.values = def.values;
  }
  return JSON.stringify(minimal);
}

/**
 * Inline coercion helper — copied verbatim into generated files so they have
 * zero runtime imports from the `envsync` package.
 */
const INLINE_COERCE = `
function __coerce(value: string | undefined, def: { type: string, default?: unknown, values?: string[] }) {
  if (value === undefined || value === "") {
    return def.default !== undefined ? def.default : undefined;
  }
  switch (def.type) {
    case "string": case "url": case "email": case "enum": return value;
    case "number": { const n = Number(value); return isNaN(n) ? value : n; }
    case "boolean": {
      if (typeof value !== "string") return value;
      const l = value.toLowerCase();
      if (l === "true" || l === "1" || l === "yes") return true;
      if (l === "false" || l === "0" || l === "no") return false;
      return value;
    }
    case "array": {
      try {
        if (typeof value === "string" && value.startsWith("[") && value.endsWith("]")) return JSON.parse(value);
        return typeof value === "string" ? value.split(",").map((v: string) => v.trim()).filter(Boolean) : value;
      } catch { return value; }
    }
    case "json": { try { return JSON.parse(value); } catch { return value; } }
    default: return value;
  }
}
`;

export function generateServerEnv(config: SchemaConfig, outDir: string, _configPath: string) {
  // Validate all keys before touching the file system
  if (config.server) {
    for (const key of Object.keys(config.server)) {
      assertSafeIdentifier(key, "server");
    }
  }

  let code = `/* eslint-disable */\n/* prettier-ignore */\n// Generated by EnvSync — do not edit manually\n\n`;

  // Guard against importing in client bundle
  code += `if (typeof window !== "undefined") {\n`;
  code += `  throw new Error(${JSON.stringify("\u274C serverEnv cannot be imported in client-side code. Move this import to a Server Component or API route.")});\n`;
  code += `}\n\n`;

  // Inline coerce helper
  code += INLINE_COERCE + "\n";

  // Interface
  code += `export interface ServerEnv {\n`;
  if (config.server) {
    for (const [key, def] of Object.entries(config.server)) {
      const tsType = getFieldTsType(def);
      const optional = (def.required !== true && def.default === undefined) ? "?" : "";
      code += `  /** process.env.${key} */\n`;
      code += `  ${key}${optional}: ${tsType};\n`;
    }
  }
  code += `}\n\n`;

  // Validate required fields at module init time
  if (config.server) {
    for (const [key, def] of Object.entries(config.server)) {
      if (def.required === true) {
        code += `if (!process.env[${JSON.stringify(key)}]) {\n`;
        code += `  throw new Error(${JSON.stringify(`\u274C Missing required server env var: ${key}`)});\n`;
        code += `}\n`;
      }
    }
  }
  code += `\n`;

  // Export the serverEnv object
  code += `export const serverEnv: ServerEnv = {\n`;
  if (config.server) {
    for (const [key, def] of Object.entries(config.server)) {
      const defJson = serializeDefForRuntime(def);
      code += `  get ${key}() { return __coerce(process.env[${JSON.stringify(key)}], ${defJson}); },\n`;
    }
  }
  code += `} as unknown as ServerEnv;\n`;

  const outPath = path.join(outDir, "server-env.ts");
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }
  fs.writeFileSync(outPath, code, "utf-8");
  return outPath;
}

export function generateClientEnv(config: SchemaConfig, outDir: string, _configPath: string) {
  const framework = config.framework || "none";
  const autoPrefix = config.autoPrefix ?? false;

  // Validate all keys before touching the file system
  if (config.client) {
    for (const key of Object.keys(config.client)) {
      assertSafeIdentifier(key, "client");
    }
  }

  let code = `/* eslint-disable */\n/* prettier-ignore */\n// Generated by EnvSync — do not edit manually\n\n`;

  // Inline coerce helper
  code += INLINE_COERCE + "\n";

  // Interface
  code += `export interface ClientEnv {\n`;
  if (config.client) {
    for (const [key, def] of Object.entries(config.client)) {
      const tsType = getFieldTsType(def);
      const optional = (def.required !== true && def.default === undefined) ? "?" : "";
      let actualKey = key;
      if (autoPrefix && framework !== "none") {
        const prefix = PREFIX_MAP[framework];
        if (prefix && !key.startsWith(prefix)) actualKey = `${prefix}${key}`;
      }
      code += `  /** process.env.${actualKey} */\n`;
      code += `  ${key}${optional}: ${tsType};\n`;
    }
  }
  code += `}\n\n`;

  // Export the clientEnv object
  code += `export const clientEnv: ClientEnv = {\n`;
  if (config.client) {
    for (const [key, def] of Object.entries(config.client)) {
      let envKey = key;
      if (autoPrefix && framework !== "none") {
        const prefix = PREFIX_MAP[framework];
        if (prefix && !key.startsWith(prefix)) envKey = `${prefix}${key}`;
      }
      // Minimal runtime def — no metadata leaked to the client bundle
      const defJson = serializeDefForRuntime(def);
      code += `  get ${key}() { return __coerce(process.env[${JSON.stringify(envKey)}], ${defJson}); },\n`;
    }
  }
  code += `} as unknown as ClientEnv;\n`;

  const outPath = path.join(outDir, "client-env.ts");
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }
  fs.writeFileSync(outPath, code, "utf-8");
  return outPath;
}

export function generateEnvReexport(_outDir: string) {
  // Intentionally empty — we keep server and client env files separate for security boundaries.
}
