import fs from "fs";
import path from "path";
import pc from "picocolors";
import { SchemaConfig, FieldDef, Framework } from "./types";

const PREFIX_MAP: Record<string, string> = {
  nextjs: "NEXT_PUBLIC_",
  vite: "VITE_",
  cra: "REACT_APP_",
  sveltekit: "PUBLIC_",
  nuxt: "NUXT_PUBLIC_",
};

function getFieldTsType(def: FieldDef): string {
  switch (def.type) {
    case "string":
    case "url":
    case "email":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      return "any[]";
    case "json":
      return "Record<string, any>";
    case "enum":
      return def.values.map(v => `"${v}"`).join(" | ");
    default:
      return "any";
  }
}

export function generateServerEnv(config: SchemaConfig, outDir: string, configPath: string) {
  const relativeConfigPath = path.relative(outDir, configPath).replace(/\\/g, "/").replace(/\.ts$/, "");
  
  let code = `/* eslint-disable */\n/* prettier-ignore */\n// Generated by EnvSync\n\n`;
  
  code += `import { validateSchema } from "envsync";\n`;
  code += `import config from "${relativeConfigPath}";\n\n`;
  
  code += `export interface ServerEnv {\n`;
  if (config.server) {
    for (const [key, def] of Object.entries(config.server)) {
      const tsType = getFieldTsType(def);
      const isRequired = def.required === true;
      const hasDefault = def.default !== undefined;
      const optional = (!isRequired && !hasDefault) ? "?" : "";
      code += `  ${key}${optional}: ${tsType};\n`;
    }
  }
  code += `}\n\n`;
  
  // Guard against importing in client bundle
  code += `if (typeof window !== "undefined") {\n`;
  code += `  throw new Error("❌ Cannot import serverEnv into client bundle.");\n`;
  code += `}\n\n`;
  
  code += `const { server, success } = validateSchema(config);\n`;
  code += `if (!success) {\n`;
  code += `  console.error("❌ Invalid environment variables");\n`;
  code += `  process.exit(1);\n`;
  code += `}\n\n`;
  
  code += `export const serverEnv: ServerEnv = server.data as unknown as ServerEnv;\n`;

  const outPath = path.join(outDir, "server-env.ts");
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }
  fs.writeFileSync(outPath, code, "utf-8");
  return outPath;
}

export function generateClientEnv(config: SchemaConfig, outDir: string, configPath: string) {
  const relativeConfigPath = path.relative(outDir, configPath).replace(/\\/g, "/").replace(/\.ts$/, "");
  const framework = config.framework || "none";
  const autoPrefix = config.autoPrefix ?? false;
  
  let code = `/* eslint-disable */\n/* prettier-ignore */\n// Generated by EnvSync\n\n`;
  
  // Guard against importing in server environments? 
  // No, the security boundary is the other way: serverEnv in client code.
  // Actually, clientEnv can be imported anywhere.
  
  code += `import { coerceValue } from "envsync";\n`;
  code += `import config from "${relativeConfigPath}";\n\n`;

  code += `export interface ClientEnv {\n`;
  if (config.client) {
    for (const [key, def] of Object.entries(config.client)) {
      const tsType = getFieldTsType(def);
      const isRequired = def.required === true;
      const hasDefault = def.default !== undefined;
      const optional = (!isRequired && !hasDefault) ? "?" : "";
      
      let actualKey = key;
      if (autoPrefix && framework !== "none") {
        const prefix = PREFIX_MAP[framework];
        if (prefix && !key.startsWith(prefix)) {
          actualKey = `${prefix}${key}`;
        }
      }
      
      code += `  /**\n`;
      code += `   * Mapped from ${actualKey}\n`;
      code += `   */\n`;
      code += `  ${key}${optional}: ${tsType};\n`;
    }
  }
  code += `}\n\n`;

  code += `export const clientEnv: ClientEnv = {\n`;
  if (config.client) {
    for (const [key, def] of Object.entries(config.client)) {
      let envKey = key;
      if (autoPrefix && framework !== "none") {
        const prefix = PREFIX_MAP[framework];
        if (prefix && !key.startsWith(prefix)) {
          envKey = `${prefix}${key}`;
        }
      }
      
      // We must use process.env.KEY exactly as written for bundlers to statically analyze
      code += `  get ${key}() {\n`;
      code += `    return coerceValue(process.env.${envKey}, config.client!.${key});\n`;
      code += `  },\n`;
    }
  }
  code += `} as unknown as ClientEnv;\n`;

  const outPath = path.join(outDir, "client-env.ts");
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }
  fs.writeFileSync(outPath, code, "utf-8");
  return outPath;
}

export function generateEnvReexport(outDir: string) {
  let code = `/* eslint-disable */\n/* prettier-ignore */\n// Generated by EnvSync\n\n`;
  
  // This file just re-exports for convenience, but developers should import from client or server specifically
  // Wait, if they import from env.ts, they might leak server to client.
  // Plan says:
  // src/config/
  // ├── server-env.ts
  // └── client-env.ts
  // No env.ts index file, to enforce boundaries.
  // Actually plan phase 2.1 says: `Create src/config/env.ts re-export file`
  // Wait, if it re-exports both, bundlers might leak it. 
  // Let's create an env.ts that exports both, but we will have an AST check. 
  // Actually, later in plan 2.1 it says scaffold `src/config/env.ts`. But in 2.3 it says `Detect client-side import of serverEnv`.
  // If we just generate client-env and server-env directly, it's safer. Let's stick to them separated.
}
